Car Dealership (with MySql)/GuildCars.UI/Models/LoanCalculatorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GuildCars.UI.Models
{
    public class LoanCalculatorViewModel
    {
        public double LoanPrincipal { get; set; }
        public double InterestRate { get; set; }
        public double LoanLengthInMonths { get; set; }
        public double LoanLengthInYears { get; set; }
        public double MonthlyPayments { get; set; }
        public double TotalLoanAmount { get; set; }
        public double TotalInterestPaid { get; set; }

        public double CompareLoanPrincipal { get; set; }
        public double CompareInterestRate { get; set; }
        public double CompareLoanLengthInMonths { get; set; }
        public double CompareLoanLengthInYears { get; set; }

        public double CompareMonthlyPayments { get; set; }
        public double CompareTotalLoanAmount { get; set; }
        public double CompareTotalInterestPaid { get; set; }

        public double DiffMonthlyPayments { get; set; }
        public double DiffTotalLoanAmount { get; set; }
        public double DiffTotalInterestPaid { get; set; }
    }
}

Car Dealership (with MySql)/GuildCars.UI/Controllers/LoanCalculatorController.cs
using GuildCars.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class LoanCalculatorController : Controller
    {
        // GET: LoanCalculator
        public ActionResult LoanCalculatorIndex()
        {
            var model = new LoanCalculatorViewModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult LoanCalculatorIndex(LoanCalculatorViewModel LoanValues)
        {
            var model = new LoanCalculatorViewModel();

            double paymentsPerYear = 12;

            model.InterestRate = LoanValues.InterestRate / 100;
            model.LoanLengthInMonths = LoanValues.LoanLengthInMonths;
            model.LoanPrincipal = LoanValues.LoanPrincipal;
            model.LoanLengthInYears = model.LoanLengthInMonths / paymentsPerYear;            

            double loanMonthlyPayment = (model.LoanPrincipal * (model.InterestRate / paymentsPerYear)) / (1 - Math.Pow(1 + (model.InterestRate / paymentsPerYear), -paymentsPerYear * model.LoanLengthInYears));

            model.TotalLoanAmount = loanMonthlyPayment * model.LoanLengthInMonths;
            model.TotalInterestPaid = model.TotalLoanAmount - model.LoanPrincipal;

            loanMonthlyPayment = Math.Round(loanMonthlyPayment, 2);
            model.TotalLoanAmount = Math.Round(model.TotalLoanAmount, 2);
            model.TotalInterestPaid = Math.Round(model.TotalInterestPaid, 2);

            model.MonthlyPayments = loanMonthlyPayment;

            //compare equations
            model.CompareInterestRate = LoanValues.CompareInterestRate / 100;
            model.CompareLoanLengthInMonths = LoanValues.CompareLoanLengthInMonths;
            model.CompareLoanPrincipal = LoanValues.CompareLoanPrincipal;
            model.CompareLoanLengthInYears = model.CompareLoanLengthInMonths / paymentsPerYear;

            double compareLoanMonthlyPayment = (model.CompareLoanPrincipal * (model.CompareInterestRate / paymentsPerYear)) / (1 - Math.Pow(1 + (model.CompareInterestRate / paymentsPerYear), -paymentsPerYear * model.CompareLoanLengthInYears));

            model.CompareTotalLoanAmount = compareLoanMonthlyPayment * model.CompareLoanLengthInMonths;
            model.CompareTotalInterestPaid = model.CompareTotalLoanAmount - model.CompareLoanPrincipal;

            compareLoanMonthlyPayment = Math.Round(compareLoanMonthlyPayment, 2);
            model.CompareTotalLoanAmount = Math.Round(model.CompareTotalLoanAmount, 2);
            model.CompareTotalInterestPaid = Math.Round(model.CompareTotalInterestPaid, 2);

            model.CompareMonthlyPayments = compareLoanMonthlyPayment;

            //difference
            model.DiffMonthlyPayments = Math.Abs(model.MonthlyPayments - model.CompareMonthlyPayments);
            model.DiffTotalLoanAmount = Math.Abs(model.TotalLoanAmount - model.CompareTotalLoanAmount);
            model.DiffTotalInterestPaid = Math.Abs(model.TotalInterestPaid - model.CompareTotalInterestPaid);
            
            return View(model);
        }
    }
}

Car Dealership (with MySql)/GuildCars.UI/Views/LoanCalculator/LoanCalculatorIndex.cshtml
@model GuildCars.UI.Models.LoanCalculatorViewModel

@{
    Layout = "~/Views/Shared/_LoanCalcLayout.cshtml";
    ViewBag.Title = "Loan Calculator Home";
}

<h2>Loan Calculator Home</h2>
<p>This is a work in progress. The goal of this project is to provide functionality while providing as much information as possible.</p>
<br /><br /><br />

<div>
    <button id="loanCompareButton" onclick="LoanCompareToggle()">Compare 2 loans</button>
</div>

<div class="col-xs-12">
@using (Html.BeginForm("LoanCalculatorIndex", "LoanCalculator", FormMethod.Post, new { id = "frmLoanCalculator" }))
{ 
    <div class="form-group col-xs-6">
            <p id="loanCompare"><b>Loan option 1</b></p>
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                <label>Loan Principal</label>
                @Html.TextBoxFor(m => m.LoanPrincipal)
            </div>
            <div class="form-group">
                <label>Interest Rate</label>
                @Html.TextBoxFor(m => m.InterestRate)
            </div>
            <div class="form-group">
                <label>Loan Length in Months</label>
                @Html.TextBoxFor(m => m.LoanLengthInMonths)
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Calculate"/>
            </div>
    </div>
    <div class="form-group col-xs-6" id="loanCompare-form">
            <p><b>Loan option 2</b></p>
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                <label>Loan Principal</label>
                @Html.TextBoxFor(m => m.CompareLoanPrincipal)
            </div>
            <div class="form-group">
                <label>Interest Rate</label>
                @Html.TextBoxFor(m => m.CompareInterestRate)
            </div>
            <div class="form-group">
                <label>Loan Length in Months</label>
                @Html.TextBoxFor(m => m.CompareLoanLengthInMonths)
            </div>
    </div>
}
    <div id="breakdown" class="col-xs-12">
        <table border="1">
            <tr>
                <td>Monthly Payment</td>
                <td><b>$@Html.ValueFor(m => m.MonthlyPayments)</b></td>
            </tr>
            <tr>
                <td>Total Paid After <b>@Html.ValueFor(m => m.LoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.TotalLoanAmount)</b></td>
            </tr>
            <tr>
                <td>Total intrest paid after <b>@Html.ValueFor(m => m.LoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.TotalInterestPaid)</b></td>
            </tr>
        </table>
    </div>

    <div id="loanCompare-table" class="col-xs-12">
        <table border="1">
            <tr>
                <th colspan="2">Loan Option 1</th>
                <th colspan="2">Loan Option 2</th>
            </tr>
            <tr>
                <td>Monthly Payment</td>
                <td><b>$@Html.ValueFor(m => m.MonthlyPayments)</b></td>
                <td>Monthly Payment</td>
                <td><b>$@Html.ValueFor(m => m.CompareMonthlyPayments)</b></td>
            </tr>
            <tr>
                <td>A difference of</td>
                <td><b>$@Html.ValueFor(m => m.DiffMonthlyPayments)</b></td>
            </tr>            
            <tr>
                <td>Total Paid After <b>@Html.ValueFor(m => m.LoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.TotalLoanAmount)</b></td>
                <td>Total Paid After <b>@Html.ValueFor(m => m.CompareLoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.CompareTotalLoanAmount)</b></td>
            </tr>
            <tr>
                <td>A difference of</td>
                <td><b>$@Html.ValueFor(m => m.DiffTotalLoanAmount)</b></td>
            </tr>
            <tr>
                <td>Total intrest paid after <b>@Html.ValueFor(m => m.LoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.TotalInterestPaid)</b></td>
                <td>Total intrest paid after <b>@Html.ValueFor(m => m.CompareLoanLengthInYears)</b> years</td>
                <td><b>$@Html.ValueFor(m => m.CompareTotalInterestPaid)</b></td>
            </tr>     
            <tr>
                <td>A difference of</td>
                <td><b>$@Html.ValueFor(m => m.DiffTotalInterestPaid)</b></td>
            </tr>       
        </table>
    </div>

</div>

@section Scripts
{
    <script>

        $(document).ready(function () {
            hidestuff();

            $("#loanCompareButton").click(function () {
                if ($("#breakdown").is(":visible"))
                {
                    $("#breakdown").hide();
                    $("#loanCompare").show();
                    $("#loanCompare-form").show();
                    $("#loanCompare-table").show();
                }
                else
                {
                    $("#breakdown").show();
                    $("#loanCompare").hide();
                    $("#loanCompare-form").hide();
                    $("#loanCompare-table").hide();
                }
            });
        });

        function hidestuff()
        {
            $("#breakdown").show();
            $("#loanCompare").hide();
            $("#loanCompare-form").hide();
            $("#loanCompare-table").hide();
        };
    </script>   
}